services:
  db: 
    hostname: dbcontainer
    build: 
      context: .
      dockerfile: Dockerfile_db
    ports:
      - 8306:3306

  web:
    build: 
      context: .
      dockerfile: Dockerfile_web
    ports:
      - 8080:80
    volumes:
      - ./php_app:/var/www/html
  flask:
    build: 
      context: .
      dockerfile: Dockerfile_flask
    ports:
      - 4000:81
    volumes:
      - ./flask_app:/var/www/html
    